# Generated by Django 4.2.16 on 2024-09-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_id_alter_progress_id_delete_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
